/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:647dc6bf-4912-46ab-b6b1-00691bb21153",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PPrRcQqjE",
    "aws_user_pools_web_client_id": "6lj6tdi317891ijl8r9jsi2ps8",
    "oauth": {},
    "aws_user_files_s3_bucket": "mybookstore9b1f64cd5740485dbb8f28c1cf5d890d01225-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ovb5qyrd75azzhvgf5p7zrx5ka.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-rmmb3e6e3zfgfoyvzowifr7yby"
};


export default awsmobile;
